package io.quarkiverse.eddi;

import java.util.LinkedHashMap;
import java.util.Map;

/**
 * A thread-safe, bounded map for managing per-user conversations in generated
 * {@code @EddiAgent} endpoints.
 * <p>
 * Uses LRU (Least Recently Used) eviction when the map exceeds the configured
 * maximum capacity, preventing unbounded memory growth while preserving the
 * most active conversations.
 * <p>
 * This is a runtime helper class used by Gizmo-generated bytecode in
 * {@code EddiAgentAnnotationProcessor}.
 */
public final class BoundedConversationMap {

    private final Map<String, Conversation> map;

    /**
     * Create a bounded conversation map with the specified maximum capacity.
     *
     * @param maxSize maximum number of conversations to retain
     */
    public BoundedConversationMap(int maxSize) {
        // LinkedHashMap with accessOrder=true implements LRU ordering
        this.map = new LinkedHashMap<>(16, 0.75f, true) {
            @Override
            protected boolean removeEldestEntry(Map.Entry<String, Conversation> eldest) {
                return size() > maxSize;
            }
        };
    }

    /**
     * Get or create a conversation for the given user ID.
     * <p>
     * If a conversation already exists for this user, it is returned and its
     * position is refreshed in the LRU order. If not, the supplier is called
     * to create a new conversation, which is then stored and returned.
     * <p>
     * If the map is at capacity, the least recently used conversation is
     * silently evicted.
     *
     * @param userId the user identifier
     * @param conversationSupplier supplier to create a new conversation if needed
     * @return the existing or newly created conversation
     */
    public synchronized Conversation getOrCreate(String userId,
            java.util.function.Supplier<Conversation> conversationSupplier) {
        Conversation existing = map.get(userId);
        if (existing != null) {
            return existing;
        }
        Conversation newConv = conversationSupplier.get();
        map.put(userId, newConv);
        return newConv;
    }

    /**
     * Get a conversation by user ID without creating a new one.
     *
     * @param userId the user identifier
     * @return the conversation, or null if not found
     */
    public synchronized Conversation get(String userId) {
        return map.get(userId);
    }

    /**
     * Store a conversation for the given user ID.
     * <p>
     * If the map is at capacity, the least recently used entry is
     * automatically evicted.
     *
     * @param userId the user identifier
     * @param conversation the conversation to store
     */
    public synchronized void put(String userId, Conversation conversation) {
        map.put(userId, conversation);
    }

    /**
     * Clear all conversations from the map.
     * <p>
     * Note: This does NOT end conversations on the EDDI server. EDDI
     * conversations persist across client restarts by design.
     */
    public synchronized void clear() {
        map.clear();
    }

    /**
     * Current number of conversations in the map.
     */
    public synchronized int size() {
        return map.size();
    }
}
