package io.quarkiverse.eddi.test;

import io.quarkiverse.eddi.annotations.EddiAgent;
import io.quarkiverse.eddi.annotations.OnMessage;

/**
 * Test fixture: a class annotated with {@code @EddiAgent} to verify that
 * the build-time annotation processor generates a working JAX-RS endpoint.
 * <p>
 * When this class is on the test classpath, {@code EddiAgentAnnotationProcessor}
 * should generate a JAX-RS resource at {@code /test-agent} that proxies requests
 * to the EDDI agent with ID "test-agent".
 */
@EddiAgent(id = "test-agent", path = "/test-agent", streaming = false)
public class SampleAgentEndpoint {

    /**
     * Pre-processing hook — proves @OnMessage hooks are invoked by the
     * generated bytecode. Prefixes the message for verification in tests.
     */
    @OnMessage
    public String preProcess(String message) {
        // Return a modified message to prove the hook was invoked
        return "[hooked] " + message;
    }
}
